[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
csv = "1"
quick-xml = {version = "0.38", features = ["serialize"]}
serde = {version = "1", features = ["derive"]}
regex = "1"
once_cell = "1"
lazy-regex = "3"
thiserror = "2"